#!/usr/bin/env bash

if [[ -f "$HOME/.bash_profile" ]]
then
  source $HOME/.bash_profile
fi

if [[ ! $(conda env list) =~ Coupon ]]
then
  conda env create -f configs/environment.yaml
fi

conda activate Coupon

python service.py "$@"
